[package]
name = "stack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.2", features = ["derive"] }
rusqlite = "0.28.0"
prettytable-rs = "^0.10"
